[package]
name = "secret-service-api"
version = "0.1.0"
edition = "2024"

[dependencies]
dbus-secret-service = "4.1.0"
anyhow = "1.0"
base64 = "0.22.1"
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
encoding_rs = "0.8"
